/** @type {import('tailwindcss').Config} */
// Tokens del design system "ActiveExam Design System" (Stitch). Mantener en sync.
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        "primary": "#4241bc",
        "primary-container": "#5b5bd6",
        "on-primary": "#ffffff",
        "on-primary-container": "#edeaff",
        "primary-fixed": "#e2dfff",
        "primary-fixed-dim": "#c1c1ff",
        "on-primary-fixed": "#0a006b",
        "on-primary-fixed-variant": "#3533b0",
        "inverse-primary": "#c1c1ff",
        "secondary": "#5845ca",
        "secondary-container": "#7260e5",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#fffbff",
        "secondary-fixed": "#e5deff",
        "secondary-fixed-dim": "#c7bfff",
        "on-secondary-fixed": "#180065",
        "on-secondary-fixed-variant": "#432bb4",
        "tertiary": "#515067",
        "tertiary-container": "#696880",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#ece9ff",
        "tertiary-fixed": "#e2e0fc",
        "tertiary-fixed-dim": "#c6c4df",
        "on-tertiary-fixed": "#1a1a2e",
        "on-tertiary-fixed-variant": "#45455b",
        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "surface": "#f9f9fd",
        "surface-dim": "#d9dade",
        "surface-bright": "#f9f9fd",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f3f3f7",
        "surface-container": "#ededf1",
        "surface-container-high": "#e8e8ec",
        "surface-container-highest": "#e2e2e6",
        "surface-variant": "#e2e2e6",
        "surface-tint": "#4e4ec9",
        "on-surface": "#1a1c1f",
        "on-surface-variant": "#464553",
        "inverse-surface": "#2e3034",
        "inverse-on-surface": "#f0f0f4",
        "background": "#f9f9fd",
        "on-background": "#1a1c1f",
        "outline": "#777585",
        "outline-variant": "#c7c4d6",
        // tokens de estado semántico (para badges de severidad)
        "success": "#15803d",
        "success-container": "#dcfce7",
        "warning": "#b45309",
        "warning-container": "#fef3c7",
      },
      borderRadius: {
        DEFAULT: "0.5rem",
        sm: "0.25rem",
        md: "0.75rem",
        lg: "1rem",
        xl: "1.5rem",
        full: "9999px",
      },
      spacing: {
        base: "4px",
        xs: "8px",
        sm: "12px",
        md: "16px",
        lg: "24px",
        xl: "32px",
        xxl: "48px",
        gutter: "24px",
        "container-max": "1280px",
        "sidebar-width": "260px",
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        headline: ['"Plus Jakarta Sans"', 'sans-serif'],
        "display-lg": ['"Plus Jakarta Sans"'],
        "headline-lg": ['"Plus Jakarta Sans"'],
        "headline-md": ['"Plus Jakarta Sans"'],
        "title-lg": ['"Plus Jakarta Sans"'],
        "body-lg": ['Inter'],
        "body-md": ['Inter'],
        "label-md": ['Inter'],
        "label-sm": ['Inter'],
      },
      fontSize: {
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "title-lg": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-md": ["15px", { lineHeight: "22px", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "600" }],
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "500" }],
      },
      maxWidth: {
        "container-max": "1280px",
      },
      boxShadow: {
        card: "0 1px 2px rgba(26,28,31,0.04), 0 4px 16px -8px rgba(26,28,31,0.06)",
        "card-lg": "0 40px 100px -20px rgba(26,28,31,0.06), 0 10px 40px -10px rgba(26,28,31,0.04)",
      },
    },
  },
  plugins: [],
}
